<a href="https://colab.research.google.com/github/alexsandoval05/Revenue-sustainability-Chrysal/blob/main/chrysal_profit_sustainability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

df1 = pd.read_csv("/content/Tabla1_Chrysal_Sustainability_v2.csv")
df2 = pd.read_csv("/content/Tabla2_Marketing_Campaign.csv")
df3 = pd.read_csv("/content/Tabla3_Costs_v2.csv")

In [ ]:
df1.head()

,Sales_order_number,Date,Country,Product_reference,Campaign_ID,Category_product,Sales_revenue_USD,Production_cost_USD,Customer_ID
0,SO-000001,2024-02-01,Holanda,Chrysal Grow X,4,Fungicida,127316.56,57858.21,1
1,SO-000002,2025-01-01,Kenya,Chrysal Flora F,3,Nutricional,28100.09,18200.66,2
2,SO-000003,2022-05-01,Ecuador,Chrysal Flora F,4,Insecticida,222096.76,101783.75,3
3,SO-000004,2024-05-01,Kenya,Chrysal Flora F,3,Nutricional,114488.78,73680.46,4
4,SO-000005,2024-04-01,Colombia,Chrysal Grow X,2,Insecticida,140394.64,78617.18,5

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Sales_order_number   700 non-null    object
 1   Date                 700 non-null    object
 2   Country              700 non-null    object
 3   Product_reference    700 non-null    object
 4   Campaign_ID          700 non-null    int64
 5   Category_product     700 non-null    object
 6   Sales_revenue_USD    630 non-null    float64
 7   Production_cost_USD  700 non-null    float64
 8   Customer_ID          700 non-null    int64
dtypes: float64(2), int64(2), object(5)
memory usage: 49.3+ KB

In [ ]:
df2.head()

   Marketing_cost  Campaign_ID Marketing_campaign_type
0          6751.0            4            Social Media
1             NaN            3   Influencers Agrícolas
2             NaN            4            Social Media
3          6751.0            3   Influencers Agrícolas
4          6751.0            2          Field Campaign

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Marketing_cost           4 non-null      float64
 1   Campaign_ID              8 non-null      int64
 2   Marketing_campaign_type  8 non-null      object
dtypes: float64(1), int64(1), object(1)
memory usage: 324.0+ bytes

In [ ]:
df3.head()

,Sales_order_number,Product_reference,Production_cost,Waste_kg,Disposal_waste_cost
0,SO-000001,Chrysal Grow X,57858.21,750.32,375.160
1,SO-000002,Chrysal Flora F,18200.66,209.94,104.970
2,SO-000003,Chrysal Flora F,101783.75,882.49,441.245
3,SO-000004,Chrysal Flora F,73680.46,982.56,491.280
4,SO-000005,Chrysal Grow X,78617.18,582.48,291.240

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Sales_order_number   700 non-null    object
 1   Product_reference    700 non-null    object
 2   Production_cost      700 non-null    float64
 3   Waste_kg             665 non-null    float64
 4   Disposal_waste_cost  665 non-null    float64
dtypes: float64(3), object(2)
memory usage: 27.5+ KB

In [ ]:
df3.nunique()

Sales_order_number     700
Product_reference        5
Production_cost        700
Waste_kg               664
Disposal_waste_cost    664
dtype: int64