<a href="https://colab.research.google.com/github/alexsandoval05/Revenue-sustainability-Chrysal/blob/main/chrysal_profit_sustainability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  **Análisis de utilidades de implementación de proyectos de sostenibilidad en Chrysal**
OBJETIVO: Definir rentabilidad anual en la implementación de proyectos de sostenibilidad y revisar si la inversion esta generando mayores ingresos.

## 1- Visión General

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

df1 = pd.read_csv("/content/Tabla1_Chrysal_Sustainability.csv")
df2 = pd.read_csv("/content/Tabla2_Marketing_Campaign.csv")
df3 = pd.read_csv("/content/Tabla3_Costs.csv")

In [2]:
df1_clean = df1.copy()
df2_clean = df2.copy()
df3_clean = df3.copy()

In [3]:
df1_clean.head()

,Sales_order_number,Date,Country,Product_reference,Campaign_ID,Category_product,Sales_revenue_USD,Production_cost_USD,Customer_ID
0,SO-000001,2024-02-01,Holanda,Chrysal Grow X,4,Fungicida,127316.56,57858.21,1
1,SO-000002,2025-01-01,Kenya,Chrysal Flora F,3,Nutricional,28100.09,18200.66,2
2,SO-000003,2022-05-01,Ecuador,Chrysal Flora F,4,Insecticida,222096.76,101783.75,3
3,SO-000004,2024-05-01,Kenya,Chrysal Flora F,3,Nutricional,114488.78,73680.46,4
4,SO-000005,2024-04-01,Colombia,Chrysal Grow X,2,Insecticida,140394.64,78617.18,5

In [4]:
df1_clean["Date"] = pd.to_datetime(df1_clean["Date"], errors="coerce", utc=True)
df1_clean["Year"]  = df1_clean["Date"].dt.year
df1_clean["Month"] = df1_clean["Date"].dt.month
df1_clean.head()

,Sales_order_number,Date,Country,Product_reference,Campaign_ID,Category_product,Sales_revenue_USD,Production_cost_USD,Customer_ID,Year,Month
0,SO-000001,2024-02-01 00:00:00+00:00,Holanda,Chrysal Grow X,4,Fungicida,127316.56,57858.21,1,2024,2
1,SO-000002,2025-01-01 00:00:00+00:00,Kenya,Chrysal Flora F,3,Nutricional,28100.09,18200.66,2,2025,1
2,SO-000003,2022-05-01 00:00:00+00:00,Ecuador,Chrysal Flora F,4,Insecticida,222096.76,101783.75,3,2022,5
3,SO-000004,2024-05-01 00:00:00+00:00,Kenya,Chrysal Flora F,3,Nutricional,114488.78,73680.46,4,2024,5
4,SO-000005,2024-04-01 00:00:00+00:00,Colombia,Chrysal Grow X,2,Insecticida,140394.64,78617.18,5,2024,4

In [5]:
df1_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Sales_order_number   700 non-null    object
 1   Date                 700 non-null    datetime64[ns, UTC]
 2   Country              700 non-null    object
 3   Product_reference    700 non-null    object
 4   Campaign_ID          700 non-null    int64
 5   Category_product     700 non-null    object
 6   Sales_revenue_USD    630 non-null    float64
 7   Production_cost_USD  700 non-null    float64
 8   Customer_ID          700 non-null    int64
 9   Year                 700 non-null    int32
 10  Month                700 non-null    int32
dtypes: datetime64[ns, UTC](1), float64(2), int32(2), int64(2), object(4)
memory usage: 54.8+ KB

In [6]:
df2_clean.head()

   Marketing_cost  Campaign_ID Marketing_campaign_type
0         11000.0            4            Social Media
1          3000.0            3        Influencers Agro
2         11000.0            4            Social Media
3          3000.0            3        Influencers Agro
4         60000.0            2          Field Campaign

In [7]:
df2_clean["Marketing_campaign_type"].value_counts()

Marketing_campaign_type
Social Media        2
Influencers Agro    2
Field Campaign      2
Email Marketing     2
Name: count, dtype: int64

In [8]:
df2_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Marketing_cost           8 non-null      float64
 1   Campaign_ID              8 non-null      int64
 2   Marketing_campaign_type  8 non-null      object
dtypes: float64(1), int64(1), object(1)
memory usage: 324.0+ bytes

In [9]:
df3_clean.head()

,Sales_order_number,Product_reference,Production_cost,Waste_kg,Disposal_waste_cost
0,SO-000001,Chrysal Grow X,57858.21,750.32,375.160
1,SO-000002,Chrysal Flora F,18200.66,209.94,104.970
2,SO-000003,Chrysal Flora F,101783.75,882.49,441.245
3,SO-000004,Chrysal Flora F,73680.46,982.56,491.280
4,SO-000005,Chrysal Grow X,78617.18,582.48,291.240

In [10]:
df3_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Sales_order_number   700 non-null    object
 1   Product_reference    700 non-null    object
 2   Production_cost      700 non-null    float64
 3   Waste_kg             665 non-null    float64
 4   Disposal_waste_cost  665 non-null    float64
dtypes: float64(3), object(2)
memory usage: 27.5+ KB

In [11]:
df3_clean.nunique()

Sales_order_number     700
Product_reference        5
Production_cost        700
Waste_kg               664
Disposal_waste_cost    664
dtype: int64

# 2- Estadistica Descriptiva

In [12]:
display(df1_clean.describe())
display(df2_clean.describe())
display(df3_clean.describe())

,Campaign_ID,Sales_revenue_USD,Production_cost_USD,Customer_ID,Year,Month
count,700.000000,630.000000,700.000000,700.00000,700.000000,700.000000
mean,2.537143,94651.089063,51202.551386,350.50000,2023.560000,2.997143
std,1.130937,51459.167383,29005.844290,202.21688,1.136267,1.447208
min,1.000000,4838.780000,2103.090000,1.00000,2022.000000,1.000000
25%,2.000000,52970.632500,27831.665000,175.75000,2023.000000,2.000000
50%,3.000000,95928.995000,51334.860000,350.50000,2024.000000,3.000000
75%,4.000000,134256.020000,73362.980000,525.25000,2025.000000,4.000000
max,4.000000,222096.760000,135566.840000,700.00000,2025.000000,5.000000

       Marketing_cost  Campaign_ID
count        8.000000     8.000000
mean     19500.000000     2.500000
std      25213.375135     1.195229
min       3000.000000     1.000000
25%       3750.000000     1.750000
50%       7500.000000     2.500000
75%      23250.000000     3.250000
max      60000.000000     4.000000

       Production_cost     Waste_kg  Disposal_waste_cost
count       700.000000   665.000000           665.000000
mean      51202.551386   914.770075           457.385038
std       29005.844290   616.570450           308.285225
min        2103.090000    24.210000            12.105000
25%       27831.665000   404.660000           202.330000
50%       51334.860000   806.690000           403.345000
75%       73362.980000  1312.180000           656.090000
max      135566.840000  2737.920000          1368.960000

In [13]:
columnas_categoricas_1 = df1_clean[['Country','Product_reference','Category_product']]
columnas_categoricas_2 = df2_clean[['Marketing_campaign_type']]

display(columnas_categoricas_1.describe())
display(columnas_categoricas_2.describe())

        Country Product_reference Category_product
count       700               700              700
unique        4                 5                5
top     Ecuador   Chrysal Flora F      Nutricional
freq        188               154              157

       Marketing_campaign_type
count                        8
unique                       4
top               Social Media
freq                         2

In [15]:
for col in columnas_categoricas_1:
    print(col)
    print(df1_clean[col].value_counts())
    print()

Country
Country
Ecuador     188
Colombia    177
Holanda     175
Kenya       160
Name: count, dtype: int64

Product_reference
Product_reference
Chrysal Flora F      154
Chrysal Root R       149
Chrysal Protect Y    148
Chrysal Grow X       139
Chrysal Boost Z      110
Name: count, dtype: int64

Category_product
Category_product
Nutricional                 157
Fertilizante                145
Insecticida                 140
Regulador de crecimiento    133
Fungicida                   125
Name: count, dtype: int64

In [16]:
print(df2_clean["Marketing_campaign_type"].value_counts())

Marketing_campaign_type
Social Media        2
Influencers Agro    2
Field Campaign      2
Email Marketing     2
Name: count, dtype: int64

**CONCLUSION DE ANALISIS:**

De acuerdo a este conteo de columnas **categoricas dominantes**  **NO** se evidencia una afectacion especifica por alguna categoria evaluada.

## 3- Visualizacion Diagnóstica

In [ ]:
df_paises = df1_clean[(df1_clean['Country']=='Colombia') |
                  (df1_clean['Country']=='Holanda') |
                  (df1_clean['Country']=='Kenya') |
                  (df1_clean['Country']=='Ecuador')
]
df_paises

In [ ]:
sns.boxplot(data=df_paises, x="Country", y="Sales_revenue_USD")
plt.title(f'Revenue Boxplot per Country')
plt.show()

In [ ]:
sns.boxplot(data=df_paises, x="Year", y="Sales_revenue_USD")
plt.title(f'Revenue Boxplot per Year')
plt.show()

##4- Identificacion formal de Outliers

##5 - Limpieza automatica por pipeline

In [ ]:
def df_clean_1(df1, numeric_cols, categorical_cols):

##6- Unificación tabla de interes para calculos de % Profit y % ROI